# -*- coding: utf-8 -*-
"""202020815_김영훈.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gs1Mb8qg5BKz7O-PwPzLv6Z-D3XJlVc2
"""

from urllib.request import urlopen
from bs4 import BeautifulSoup

html = urlopen("https://news.naver.com/")

bsObject = BeautifulSoup(html, "html.parser")

#기사 가져오기
for link in bsObject.find_all('a'):
  print(link.text.strip(), link.get('href'))

